trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'windows-2019'

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false